version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=elec123
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  electricity-app-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./Electricity-app-frontend
    volumes:
      - /Elec-app/node_modules
      - ./Electricity-app-frontend:/Elec-app
  electricity-app-backend:
    build:
      dockerfile: Dockerfile
      context: ./Electricity-app-backend
    volumes:
      - /Elec-app/node_modules
      - ./Electricity-app-backend:/Elec-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
